version: '2'
services:
  identity:
    container_name: truesparrow.e2e-tests.identity
    image: eu.gcr.io/chmsqrt2-truesparrow-common/identity:latest
    ports:
     - 10001:10001
    env_file:
     - ./.env
    extra_hosts:
     - "postgres.test.truesparrow:172.16.123.1"
  content:
    container_name: truesparrow.e2e-tests.content
    image: eu.gcr.io/chmsqrt2-truesparrow-common/content:latest
    ports:
     - 10002:10002
    env_file:
     - ./.env
    extra_hosts:
     - "postgres.test.truesparrow:172.16.123.1"
     - "identity.test.truesparrow:172.16.123.1"
