kind: Service
apiVersion: v1
metadata:
  name: adminfe
spec:
  selector:
    service: adminfe
    tier: frontend
  type: NodePort
  ports:
  - protocol: TCP
    name: http
    port: 80
    targetPort: 10003
